CREATE SCHEMA calculator;

SET SCHEMA calculator;

-- create sample table
CREATE COLUMN TABLE expression
(
  id            BIGINT           NOT NULL primary key GENERATED BY DEFAULT AS IDENTITY,
  expression    VARCHAR(50) ,
  result        double ,
  error         varchar(100)
);
